### PR TITLE
Release 100.13.0.1

### PR DESCRIPTION
**Pull request by vquach2404**
```txt
The following samples have been added:

• Display information > Filter by time extent
• Features > Toggle between feature request modes
• Layers > Export vector tiles
• Layers > Select ENC features
• Maps > Display a map SwiftUI

The following samples have been updated:

• Display information > Sketch on the map
• Geometry > Nearest vertex
• Layers > OpenStreetMap layer

The following samples have been removed:

• Features > Service feature table (cache)
• Features > Service feature table (manual cache)
• Features > Service feature table (no cache)
• Layers > ArcGIS vector tiled layer (URL)

In addition, this release includes the following changes:

• Updated app info page
• Updated main README with instructions for installing SDK manually
• Fixed various bugs in the following samples: Identify raster cell, Map reference scale, and Show legend
• Updated READMEs
• Updated Display KML network links service
```

### CODE REVIEW

**Review by yo1995 — COMMENTED** [review]
~~The changes look good, but the release notes are not correct - they seem to overlap a lot with the [12.0.2](https://github.com/Esri/arcgis-runtime-samples-ios/releases/tag/v100.12.0.2) notes. Did you paste the wrong notes?~~

**Comment by vquach2404** [comment]
> The changes look good, but the release notes are not correct - they seem to overlap a lot with the [12.0.2](https://github.com/Esri/arcgis-runtime-samples-ios/releases/tag/v100.12.0.2) notes. Did you paste the wrong notes?

Mike stated that the U13 release notes should include 100.12.0.2:
> Probably unnecessary, but to be as explicit as possible in writing:
Release notes pattern
100.12.0.1 = Update 12 release notes
100.12.0.2 + 100.13.0.1 = U13 notes
100.13.0.2 + 100.14.0.1 = U14 notes
etc.

**Comment by yo1995** [comment]
Ohh that makes sense. Let me make some slight adjustments to the notes before approval.

**Review by yo1995 — DISMISSED** [review]

**Review by yo1995 — APPROVED** [review]

**Review by saratchandrakarumuri — APPROVED** [review]
Looking good...

**Pull request merged**
