### PR TITLE
Symbol samples

### PR DESCRIPTION
**Pull request by singhgag**
Added following samples:
- Picture marker symbols 
- Simple marker symbol

### CODE REVIEW

**Comment by maryharvey** [comment]
@singhgag Can you update the code comments so that the func addPictureMarkerSymbolFromImage refers to the "PinBlueStar" and not the campsite See here:

```      
//location for camp site
//graphic for camp site
```
Simple Marker Symbol. Can you make the marker symbol a bit bigger and a different color. The vibrancy of the red and green will make it difficult for color blind people to see.

**Comment by singhgag** [comment]
@maryharvey what color should it be then? Also post in the common samples issue.

**Comment by singhgag** [comment]
@maryharvey I have made the changes.

**Comment by dg0yal** [comment]
@singhgag Can you update this branch to remove the conflicts

**Comment by singhgag** [comment]
@dg0yal You can merge this one too.

**Pull request merged**
