### PR TITLE
Update: App Icon

### PR DESCRIPTION
**Pull request by yo1995**
**Description**: Update to the new purple icon from the creative lab.  
Should also consider if the viewer need to match the color scheme.

**Ref**: /common-samples/issues/1723

Note: This PR can be reviewed at this time, and merged later if we decide to adopt the new color scheme.

### CODE REVIEW

**Comment by yo1995** [comment]
Refer to #227 to better examine the consistency of style change.

**Comment by yo1995** [comment]
Should we include this PR as part of Dark Mode update? 

We can make changes to the base color schema of the app (blue -> purple) during this process and make sure it looks good. 🤔

**Comment by vquach2404** [comment]
> Should we include this PR as part of Dark Mode update?
> 
> We can make changes to the base color schema of the app (blue -> purple) during this process and make sure it looks good. 🤔

I think that's a good idea!

**Comment by yo1995** [comment]
A nudge to this thread: how do you think the approach above? Should we merge this change first? 💭

**Comment by philium** [comment]
It might be nice to update the theme all at once. It seems like changing the app's primary color and the color of the app icons all goes together.

**Comment by yo1995** [comment]
> It might be nice to update the theme all at once. It seems like changing the app's primary color and the color of the app icons all goes together.

Sounds reasonable. I'll close this PR and mark #915 ready for review.

**Pull request closed without merging**
