### PR TITLE
Updated ReadMe to iOS 8 in the Note

### PR DESCRIPTION
**Pull request by maryharvey**
In Display a Devlce Location Sample the Note should read "Note: As of iOS 8, you are required..."
Updated the copyright description in 2 samples.

### CODE REVIEW

**Comment by singhgag** [comment]
@maryharvey Its supposed to be iOS 7.

**Comment by maryharvey** [comment]
@dg0yal @singhgag Please confirm - https://devtopia.esri.com/runtime/cocoa-common-sdk/issues/296
whether this is iOS 7 or iOS 8

**Comment by singhgag** [comment]
Got confused. It should be iOS 8.

**Comment by singhgag** [comment]
@maryharvey can you resolve the merge conflicts?

**Pull request closed without merging**
