### PR TITLE
New 3D Samples

### PR DESCRIPTION
**Pull request by singhgag**
- Display a scene
- Extrude graphics
- 3D symbols
- Surface placements

### CODE REVIEW

**Comment by dlednik** [comment]
@singhgag three finger swipe is not enabled in Surface placement sample. So you can't tilt the camera. Don't know if that is intentional.

But I get consistent crashes with 3D symbol sample. Sometimes I only need to zoom out. Or if that doesn't trip it I pan around a bit.

trace from three crashes. I'll test on latest build to check if it's still present and log an issue.
```
(lldb) bt
* thread #440: tid = 0xa9120, 0x0000000190869f28 libGPUSupportMercury.dylib`gpus_ReturnGuiltyForHardwareRestart + 12, queue = 'com.esri.arcgis.mapRendererQ', stop reason = EXC_BAD_ACCESS (code=1, address=0x1)
  * frame #0: 0x0000000190869f28 libGPUSupportMercury.dylib`gpus_ReturnGuiltyForHardwareRestart + 12
    frame #1: 0x000000019086aec4 libGPUSupportMercury.dylib`gpusSubmitDataBuffers + 172
    frame #2: 0x0000000194a8b1e4 GLEngine`gliPresentViewES_Exec + 176
    frame #3: 0x0000000194a8b0fc GLEngine`gliPresentViewES + 84
    frame #4: 0x000000018441bc44 OpenGLES`-[EAGLContext presentRenderbuffer:] + 72
    frame #5: 0x00000001042d40e0 libglInterpose.dylib`EAGLContext_presentRenderbuffer(EAGLContext*, objc_selector*, unsigned long) + 360
    frame #6: 0x000000010027a5e8 arcgis-ios-sdk-samples`-[AGSGeoViewRenderer doDraw] + 400
    frame #7: 0x0000000104a35a7c libdispatch.dylib`_dispatch_call_block_and_release + 24
    frame #8: 0x0000000104a35a3c libdispatch.dylib`_dispatch_client_callout + 16
    frame #9: 0x0000000104a42554 libdispatch.dylib`_dispatch_queue_drain + 1036
    frame #10: 0x0000000104a3972c libdispatch.dylib`_dispatch_queue_invoke + 464
    frame #11: 0x0000000104a4466c libdispatch.dylib`_dispatch_root_queue_drain + 760
    frame #12: 0x0000000104a44364 libdispatch.dylib`_dispatch_worker_thread3 + 132
    frame #13: 0x0000000181f21470 libsystem_pthread.dylib`_pthread_wqthread + 1092
    frame #14: 0x0000000181f21020 libsystem_pthread.dylib`start_wqthread + 4
(lldb) 


(lldb) bt
* thread #36: tid = 0xa93dc, 0x0000000190869f28 libGPUSupportMercury.dylib`gpus_ReturnGuiltyForHardwareRestart + 12, queue = 'com.esri.arcgis.mapRendererQ', stop reason = EXC_BAD_ACCESS (code=1, address=0x1)
  * frame #0: 0x0000000190869f28 libGPUSupportMercury.dylib`gpus_ReturnGuiltyForHardwareRestart + 12
    frame #1: 0x000000019086aec4 libGPUSupportMercury.dylib`gpusSubmitDataBuffers + 172
    frame #2: 0x0000000193c6f0e4 AGXGLDriver`agxuFinishContextResource + 104
    frame #3: 0x0000000193c46ad0 AGXGLDriver`glrReadFramebufferData + 1040
    frame #4: 0x00000001949cae00 GLEngine`glReadPixels_Exec + 1472
    frame #5: 0x000000010428747c libglInterpose.dylib`read_pixels(__GLIContextRec*, int, int, int, int, unsigned int, unsigned int, void*) + 356
    frame #6: 0x0000000100e6467c arcgis-ios-sdk-samples`Esri_runtimecore::HAL::Frame_buffer_ogl::read_pixels(std::__1::shared_ptr<Esri_runtimecore::HAL::Device> const&, unsigned int, unsigned int, unsigned int, unsigned int, unsigned char*) + 128
    frame #7: 0x0000000100a8dcb8 arcgis-ios-sdk-samples`Esri_runtimecore::HAL_3D::Hal_rendertarget::read_pixels(Esri_runtimecore::HAL_3D::Renderer*, int, int, int, int, unsigned char*) + 152
    frame #8: 0x0000000100a81f70 arcgis-ios-sdk-samples`Esri_runtimecore::HAL_3D::Hal_renderer::read_pixels(int, int, int, int, unsigned char*) + 68
    frame #9: 0x000000010096de4c arcgis-ios-sdk-samples`Esri_runtimecore::Map_renderer_3D::View3D::sample_depth_buffer(Esri_runtimecore::HAL_3D::Renderer*) + 640
    frame #10: 0x000000010096db60 arcgis-ios-sdk-samples`Esri_runtimecore::Map_renderer_3D::View3D::end_render(Esri_runtimecore::HAL_3D::Renderer*, Esri_runtimecore::Map_renderer_3D::Rendering_option*) + 72
    frame #11: 0x0000000100970014 arcgis-ios-sdk-samples`Esri_runtimecore::Map_renderer_3D::View3D::draw(std::__1::shared_ptr<Esri_runtimecore::HAL::Device> const&) + 400
    frame #12: 0x00000001007095d4 arcgis-ios-sdk-samples`Esri_runtimecore::Mapping::Scene_view::draw(Esri_runtimecore::Mapping::Device&) + 160
    frame #13: 0x000000010049887c arcgis-ios-sdk-samples`RT_GeoView_draw + 48
    frame #14: 0x00000001002e31c0 arcgis-ios-sdk-samples`-[RTCGeoView draw:error:] + 148
    frame #15: 0x0000000100296594 arcgis-ios-sdk-samples`-[AGSGeoViewRenderer doDraw] + 316
    frame #16: 0x0000000104a75a7c libdispatch.dylib`_dispatch_call_block_and_release + 24
    frame #17: 0x0000000104a75a3c libdispatch.dylib`_dispatch_client_callout + 16
    frame #18: 0x0000000104a82554 libdispatch.dylib`_dispatch_queue_drain + 1036
    frame #19: 0x0000000104a7972c libdispatch.dylib`_dispatch_queue_invoke + 464
    frame #20: 0x0000000104a8466c libdispatch.dylib`_dispatch_root_queue_drain + 760
    frame #21: 0x0000000104a84364 libdispatch.dylib`_dispatch_worker_thread3 + 132
    frame #22: 0x0000000181f21470 libsystem_pthread.dylib`_pthread_wqthread + 1092
    frame #23: 0x0000000181f21020 libsystem_pthread.dylib`start_wqthread + 4
(lldb) 


(lldb) bt
* thread #144: tid = 0xa9826, 0x0000000190869f28 libGPUSupportMercury.dylib`gpus_ReturnGuiltyForHardwareRestart + 12, queue = 'com.esri.arcgis.mapRendererQ', stop reason = EXC_BAD_ACCESS (code=1, address=0x1)
  * frame #0: 0x0000000190869f28 libGPUSupportMercury.dylib`gpus_ReturnGuiltyForHardwareRestart + 12
    frame #1: 0x000000019086aec4 libGPUSupportMercury.dylib`gpusSubmitDataBuffers + 172
    frame #2: 0x0000000194a8b1e4 GLEngine`gliPresentViewES_Exec + 176
    frame #3: 0x0000000194a8b0fc GLEngine`gliPresentViewES + 84
    frame #4: 0x000000018441bc44 OpenGLES`-[EAGLContext presentRenderbuffer:] + 72
    frame #5: 0x00000001042500e0 libglInterpose.dylib`EAGLContext_presentRenderbuffer(EAGLContext*, objc_selector*, unsigned long) + 360
    frame #6: 0x00000001001d65e8 arcgis-ios-sdk-samples`-[AGSGeoViewRenderer doDraw] + 400
    frame #7: 0x0000000104971a7c libdispatch.dylib`_dispatch_call_block_and_release + 24
    frame #8: 0x0000000104971a3c libdispatch.dylib`_dispatch_client_callout + 16
    frame #9: 0x000000010497e554 libdispatch.dylib`_dispatch_queue_drain + 1036
    frame #10: 0x000000010497572c libdispatch.dylib`_dispatch_queue_invoke + 464
    frame #11: 0x000000010498066c libdispatch.dylib`_dispatch_root_queue_drain + 760
    frame #12: 0x0000000104980364 libdispatch.dylib`_dispatch_worker_thread3 + 132
    frame #13: 0x0000000181f21470 libsystem_pthread.dylib`_pthread_wqthread + 1092
    frame #14: 0x0000000181f21020 libsystem_pthread.dylib`start_wqthread + 4
(lldb) 
```

**Comment by singhgag** [comment]
@dlednik 3 finger swipe should work. I don't think there is a way to enable or disable it. And before the crash, did you get any memory warnings?

**Comment by Mambix** [comment]
no, no memory warnings

**Comment by dlednik** [comment]
no, no memory warnings

**Comment by mhdostal** [comment]
@singhgag This looks good; very straightforward, helpful code comments, nicely written.

I have one comment:  the spacing around arithmetic operators is not always consistent; sometimes there are no spaces (`point.y+squareSize`) and sometimes there is a space (`squareSize + spacing`).

I think they should be consistent, with a single space on either side of the operator; this is motivated in part by personal preference, but also consistency and what we try to do in the SDK.

**Comment by singhgag** [comment]
Thanks @mhdostal for the feedback. I will make the changes.

**Comment by dg0yal** [comment]
@singhgag Images for the readme?

**Comment by singhgag** [comment]
@dg0yal They are in now.

**Pull request merged**
