### PR TITLE
New sample: Add delete related feature

### PR DESCRIPTION
**Pull request by singhgag**

### CODE REVIEW

**Comment by dg0yal** [comment]
-[ ] Can we show the name of the park that the user tapped on? It's not very intuitive that I tap on a park and see a list of species. If we can add the name, then maybe we can show a banner along the top edge of the map saying something like "Tap on a park to see its species"
- [ ] Didn't realize i could swipe a cell to delete. Can we show a visual indicator or maybe a delete action in each cell
- [ ] Can we scroll to the end of the list when the add finishes? I couldn't tell if anything was happening when i hit that button

**Comment by singhgag** [comment]
@dg0yal I have made the changes. Please take another look.

**Comment by dg0yal** [comment]
- [ ] The sample title should be "Add/Delete related features"

Also, the panel which lists related features looks better now. But wondering if we should swap the title with the name of the feature, move everything up one level. Right now there is redundant "Related features : species" both in the title and in a sub-section
screen shot 2017-06-23 at 12 15 41 pm

**Comment by singhgag** [comment]
The name of the feature might be omitted in the title. I can clear the title instead.

**Pull request merged**
