### PR TITLE
Added: Create geometries sample

### PR DESCRIPTION
**Pull request by singhgag**

### CODE REVIEW

**Comment by maryharvey** [comment]
@singhgag 
Create Geometries - Info
Can you add something in the text about the geometry builders?
Change the variable names to be multipointBuilder, polylineBuilder, polygonBuilder then its clear the methods are called from the builders and not the geometries.
(same for osx samples)

**Comment by singhgag** [comment]
@maryharvey I have made the changes. Please review.

**Comment by dg0yal** [comment]
@singhgag Can you resolve the conflicts?

**Comment by singhgag** [comment]
@dg0yal You can merge now. Once you have merged it I will update the other PR.

**Comment by dg0yal** [comment]
Done

**Pull request merged**
