### PR TITLE
[Dark Mode] Update: Maps

### PR DESCRIPTION
**Pull request by yo1995**
This PR updates the storyboards in `Maps` category to adapt to Dark Mode, and update the screenshots. All screenshots are in the latest purple color and is resized for a unified visual appearance, and compressed to save bandwidth for our repo and developer site.

Please note

- The docs for `Read a geopackage` sample are updated to remove 1 unrelated screenshot
- A src is updated to remove redundant color

The category is quite huge to review, so take your time!

### CODE REVIEW

**Review by vquach2404 — APPROVED** [review]
LGTM!

**Comment by yo1995** [comment]
Issues to fix

1. Replace the screenshot of `GenerateOfflineMapViewController` that has Naperville in title
2. Add years to `Honor mobile map package expiration date`

**Review by philium — DISMISSED** [review]

**Review by saratchandrakarumuri — APPROVED** [review]
Looks good

**Review by philium — APPROVED** [review]

**Comment by yo1995** [comment]
Sorry but I have to replace 1 screenshot with wrong title. Please take another look!

**Review by vquach2404 — APPROVED** [review]

**Review by saratchandrakarumuri — APPROVED** [review]

**Pull request merged**
