### PR TITLE
Release 100.10 AppStore

### PR DESCRIPTION
**Pull request by yo1995**
The PR will merge the latest U10 sample updates to master branch.

We'll merge this PR on Wednesday March 31st, as well as publish the release build on AppStore.

---

The new release note

```
The following samples have been added:

• Augmented reality > View hidden infrastructure in AR
• Display information > Create symbol styles from web styles
• Geometry > Buffer list
• Layers > Add ENC exchange set
• Maps > Display device location with NMEA data sources
• Route and directions > Navigate route with rerouting
• Utility network > Create load report

The following samples have been updated:

• Augmented reality > Flyover AR
• Display information > Custom dictionary style
• Edit data > Edit and sync features
• Geometry > Spatial operations
• Layers > Edit KML ground overlay
• Layers > Export tiles
• Layers > ArcGIS vector tiled layer (custom style)
• Layers > Group layers
• Layers > Apply mosaic rule to rasters
• Layers > Identify KML features
• Maps > Change basemap
• Scenes > Create terrain from local tile package
• Scenes > Add integrated mesh layer

In addition, this update includes the following changes:

• Added Dark Mode support
• Slightly improved coding style
• Updated build phases and path to the new ArcGIS Framework
• Incorporated API key and new basemap initializers
• Replaced pixelated Brest basemap
• Fixed the build error that occurs in the first clean build
• Updated the demo Sample Server used in utility network samples
```

### CODE REVIEW

**Review by dg0yal — DISMISSED** [review]

**Review by vquach2404 — APPROVED** [review]

**Comment by dg0yal** [comment]
@yo1995 i don’t seem many of the new samples in the test flight (load report, nmea, web styles)

**Comment by yo1995** [comment]
> I don’t seem many of the new samples in the test flight submission(load report, nmea, web styles). 

I didn't create a separate TestFlight `Samples Beta` app, but only upload a build to the formal [Samples app](https://apps.apple.com/us/app/arcgis-runtime-sdk-samples/id1180714771). That is to say, once you install it from TestFlight, it will overwrite the 100.9 app.

I know we decided in U9 to use the separate `Samples Beta` for comparison and internal testing, but since we are on a tight schedule (try to make the release public before this Friday), I skipped this step this time.

> Also, didn’t we have dark mode already before this update?

Nope. In U9 the app changed from blue to purple, but the Dark Mode changes are merged during U10 (Jan 27th).

**Comment by dg0yal** [comment]
Ah, I see them now

**Review by philium — DISMISSED** [review]

**Review by saratchandrakarumuri — DISMISSED** [review]

**Comment by yo1995** [comment]
Two more fixes to do before the release

- Address the issue in `Edit and sync feature` from #750 
- Update the URL for `Create load report sample` for SS7

**Comment by yo1995** [comment]
I've addressed the 2 issues from AppStore review and merged them into `v.next`. 
Now the 100.10.0 release has been approved, and you'll see the update on AppStore soon! 🎉

**Review by saratchandrakarumuri — APPROVED** [review]

**Review by philium — APPROVED** [review]

**Pull request merged**
