### PR TITLE
Show custom callout

### PR DESCRIPTION
**Pull request by ikbalyasar**
Tap on the map to get the coordinates and closer look mapview for the location in a callout. Tap again to hide it.

### CODE REVIEW

**Comment by ikbalyasarGis** [comment]
Are you able to review my codes

**Comment by ikbalyasarGis** [comment]
Hi. Can you check my codes ? Waiting Impatiently ...

**Comment by ikbalyasar** [comment]
Hi. Can you check my codes ? Waiting Impatiently ...???

**Comment by dlednik** [comment]
@dg0yal @singhgag

**Comment by ikbalyasar** [comment]
@dg0yal @singhgag is there anything you can do about it? if you did not merge @fozoglu and I would like to discard our pull requests.

**Pull request closed without merging**
