### PR TITLE
Update: Basemap constructors 1

### PR DESCRIPTION
**Pull request by yo1995**
This PR updates the basemap constructors to use the U10 new metered APIs.

This PR only includes the one-to-one mappings for the basemap constructors and shown below. 
More uncertain changes will be included in #1015 .

## Plan

Since these changes are blocked by the API key update in #1013 , all the PRs will first go to branch `basemap-updates`. 
Updates will go in several separate PRs to reduce the effort to review.
After all the basemap updates are in (no more deprecation warnings in the app), `basemap-updates` will then merge into `v.next`.

The update will go in a few separate PRs

- #1009 and #1015 : batch find-replace old API with new APIs
- A PR to update the design for `Change basemap` sample
- A PR to update `Create and save a map` sample
- A PR to update all the README and metadata with keyword `basemap`
- (under consideration) A PR to redesign the `OpenStreetMap layer` sample

---

Below is a mapping table between old and new APIs.

## Maps

AGSMap(basemap: .imagery())
AGSMap(basemapStyle: .arcGISImageryStandard)

AGSMap(basemap: .topographic())
AGSMap(basemapStyle: .arcGISTopographic)

AGSMap(basemap: .streets())
AGSMap(basemapStyle: .arcGISStreets)

AGSMap(basemap: .oceans())
AGSMap(basemapStyle: .arcGISOceans)

AGSMap(basemap: .imageryWithLabels())
AGSMap(basemapStyle: .arcGISImagery)

AGSMap(basemap: .navigationVector())
AGSMap(basemapStyle: .arcGISNavigation)

AGSMap(basemap: .lightGrayCanvas())
AGSMap(basemapStyle: .arcGISLightGrayBase)

AGSMap(basemap: .streetsNightVector())
AGSMap(basemapStyle: .arcGISStreetsNight)

AGSMap(basemap: .streetsWithReliefVector())
AGSMap(basemapStyle: .arcGISStreetsRelief)

AGSMap(basemap: .darkGrayCanvasVector())
AGSMap(basemapStyle: .arcGISDarkGrayBase)

## Scenes

For U10 the new constructors do not work well with 3D scenes, so they are not updated.

## Not Sure (not updated)

AGSMap(basemap: .streetsVector())
???

AGSMap(basemap: .lightGrayCanvasVector())
???

AGSMap(basemap: .imageryWithLabelsVector())
???

AGSMap(basemap: .topographicVector())
???

AGSMap(basemap: .nationalGeographic())
???

AGSMap(basemap: .terrainWithLabels())
???

### CODE REVIEW

**Review by vquach2404 — COMMENTED** [review]
It seems like we'll have to update some of the READMEs for these samples as well. One being [Display a map](https://github.com/Esri/arcgis-runtime-samples-ios/blob/d9b366b99ea6ad47d3e4b9a419f74c46189c824d/arcgis-ios-sdk-samples/Maps/Display%20a%20map/README.md#how-it-works).

**Comment by yo1995** [comment]
> It seems like we'll have to update some of the READMEs for these samples as well. 

Good point. I plan to search for keyword `basemap` in all README files and fix them in a separate PR (to make it smaller to review). However I don't know if that means we also need to update the internal design READMEs... 🤔

**Comment by vquach2404** [comment]
> However I don't know if that means we also need to update the internal design READMEs... 🤔

I don't think that's a priority since that is for internal use only and we are all aware of the basemap updates. We can update those if we revisit them later.

**Comment by yo1995** [comment]
A few updates to scene imagery basemaps need to be reverted.

**Review by vquach2404 — APPROVED** [review]
Looks good!

**Comment by philium** [comment]
> ## Maps
> AGSMap(basemap: .imagery())
> AGSMap(basemapStyle: .arcGISImagery)

`arcGISImagery` includes both images and labels. So the replacement style for `AGSBasemap.imagery()` is `arcGISImageryStandard`.

> AGSMap(basemap: .imageryWithLabels())
> AGSMap(basemapStyle: .arcGISImageryLabels)

`arcGISImageryLabels` is just the labels. So the replacement style for `AGSBasemap.imageryWithLabels()` is `arcGISImagery `.

> AGSMap(basemap: .lightGrayCanvas())
> AGSMap(basemapStyle: .arcGISLightGray)

`arcGISLightGray` includes labels. So the replacement style for `AGSBasemap.lightGrayCanvas()` is `arcGISLightGrayBase`.

> AGSMap(basemap: .darkGrayCanvasVector())
> AGSMap(basemapStyle: .arcGISDarkGray)

`arcGISDarkGray` includes labels. So the replacement style for `AGSBasemap.darkGrayCanvas()` is `arcGISDarkGrayBase`.

**Comment by philium** [comment]
Is this ready to be re-reviewed?

**Comment by yo1995** [comment]
> Is this ready to be re-reviewed?

Yes please!

**Review by philium — APPROVED** [review]

**Pull request merged**
