### PR TITLE
Add content beneath surface sample

### PR DESCRIPTION
**Pull request by saratchandrakarumuri**

### CODE REVIEW

**Comment by philium** [comment]
It looks like the changes from `v.next` weren't added as part of a merge operation. There isn't a merge commit, which is why those files are showing up as newly added in this PR.

I would suggest getting rid of the last commit ("Fix merge conflicts") and [rebasing](https://git-scm.com/book/en/v2/Git-Branching-Rebasing) your branch onto `v.next`. Let me know if you'd like some help with that.

**Comment by saratchandrakarumuri** [comment]
@philium Sorry for the bad commit. I reverted that and merged changes from `v.next` properly. Please review again

**Comment by philium** [comment]
@saratchandrakarumuri Thanks. I'll take a look.

**Comment by saratchandrakarumuri** [comment]
@philium Fixed filenames and readme doc as per review comments.

**Pull request merged**
