### PR TITLE
Added the touches functionality

### PR DESCRIPTION
**Pull request by singhgag**
- You can toggle it in the Settings app on apple device

### CODE REVIEW

**Comment by maryharvey** [comment]
Tested with iOS Build 1416

**Comment by maryharvey** [comment]
@singhgag Tested with Build 1457 - comments in original Issue

**Comment by mhdostal** [comment]
@singhgag Just a couple of comments

**Comment by mhdostal** [comment]
@maryharvey @singhgag has addressed all my comments.  Are you ready for this to merge?

**Comment by dg0yal** [comment]
Done.

**Pull request merged**
