### PR TITLE
Updated basemaps in samples

### PR DESCRIPTION
**Pull request by saratchandrakarumuri**
Updated basemaps in change basemap and vector tiled layer samples to match with other sample viewers

### CODE REVIEW

**Comment by saratchandrakarumuri** [comment]
@dg0yal I have already updated the screenshots for those two samples. I have updated the URLs to use https

**Comment by dg0yal** [comment]
Is it possible to change the text size of the segmented control so that  basemap names fit properly?

**Comment by saratchandrakarumuri** [comment]
@dg0yal I have changed the size of text in segmented control and I have updated the screenshot accordingly

**Comment by dg0yal** [comment]
Looks good. Just one more thing to resolve. The `Change Basemap` sample doesn't work right on iPhone 8 Plus in landscape mode 

image

**Comment by saratchandrakarumuri** [comment]
Fixed issue with landscape mode and extended blur view beyond safe area to cover whole screen on iPhoneX in landscape mode

**Pull request merged**
