### PR TITLE
added logic for local notification permissions in DownloadTileCacheSampl...

### PR DESCRIPTION
**Pull request by singhgag**
...e and OfflineFeatureEditingSample

### CODE REVIEW

**Comment by dg0yal** [comment]
@singhgag  This won't compile when building with iOS 7 SDK (which is still supported at 10.2.4)
Can you add conditional check?

**Comment by singhgag** [comment]
@dg0yal the checks are already in. It was working for me when I tested. 
Is the problem specific to swift or objC?

**Comment by dg0yal** [comment]
Your project must be compiling with iOS 8 SDK. It won't compile with iOS 7 SDK.
(I don't mean running on iOS 7 or 8 simulator, I mean the iOS SDK that your project builds with)

**Comment by singhgag** [comment]
@dg0yal done

**Pull request merged**
