### PR TITLE
New sample: Animate 3D graphic

### PR DESCRIPTION
**Pull request by singhgag**
Updated horizontal picker to accommodate for initial item selection at load.

### CODE REVIEW

**Comment by dg0yal** [comment]
The mission files don't load when I run the sample. Have the ODR been setup correctly for this sample?

**Comment by singhgag** [comment]
Delete the existing app and try again.

**Comment by dg0yal** [comment]
Nice. That worked. I will review. In the meantime, can you resolve the conflict with the proj file and update the branch.

**Comment by dg0yal** [comment]
- [ ] Turn off attribution for the overview map
- [ ] Can you put a border or a shadow around the overview map to give it a sense of depth and make it stand out from the main map. 
- [ ] Currently the popovers block interaction with the main map. Can you permit this? That way i can  change the pitch etc and see the values update in the camera settings
- [ ] Can you make the Camera Settings popover taller (on ipad) so that all the controls are in view and scrolling is not required.

**Comment by dg0yal** [comment]
Rest everything looks good

**Comment by singhgag** [comment]
@dg0yal Done with the changes. Take a look.

**Pull request merged**
