### PR TITLE
[Dark Mode] Update: Geometry

### PR DESCRIPTION
**Pull request by yo1995**
This PR updates the storyboards in `Geometry` category to adapt to Dark Mode, and update the screenshots.

### CODE REVIEW

**Review by vquach2404 — COMMENTED** [review]
These background colors in these two call outs remain the same in dark and light mode. Is this expected?
Simulator Screen Shot - iPhone 12 Pro Max - 2020-11-19 at 14 41 52
Also, the text in Project is illegible in dark mode. 
Simulator Screen Shot - iPhone 12 Pro Max - 2020-11-19 at 14 17 35

**Comment by yo1995** [comment]
I'm not quite sure what is the correct approach. Both are expected, but I won't merge this PR until we reach a consensus.
For the `Nearest vertex` sample, it uses the native `title` and `detail` properties of a callout; for the `Project` sample, it uses a custom view.

> These background colors in these two call outs remain the same in dark and light mode. Is this expected?

It is expected. Currently the callout is not Dark Mode adaptive, so the background and text colors are hardcoded.

> Also, the text in Project is illegible in dark mode.

Since the labels are in a custom (stack) view, they adapt to Dark Mode changes, whereas the callout's background color doesn't change... so it looks weird in Dark Mode.

---

@philium For now, should we hard code label text's color to black in a custom view in a callout? 
I see the attribution footer is currently being updated by Zach for Dark Mode, and I wonder if callout will also be updated soon. 😳

**Review by vquach2404 — DISMISSED** [review]
Everything else looks good, feel free to add more reviewers!

**Comment by philium** [comment]
> should we hard code label text's color to black in a custom view in a callout?

Yes, I would say change what is needed so that it displays properly now.

**Review by saratchandrakarumuri — APPROVED** [review]
Changes are good

**Review by philium — APPROVED** [review]

**Pull request merged**
